version: '2.1'

services:
  docker-node:
    image: docker-node
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    command: nodemon -L --inspect=0.0.0.0:9229
    volumes:
      - .:/usr/src/app